services:
  waitfordb:
    image: dadarek/wait-for-dependencies
    depends_on:
      - db-server
    command: db-server:5432

  db-server:
    image: postgres:13.3
    container_name: ${DB_HOST}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      TZ: "Asia/Tokyo"
    ports:
      - 5432:5432
    volumes:
      - $PWD/db_server:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 81:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    depends_on:
      - db-server

  tracking-server:
    container_name: mlflow-tracking
    build:
      context: .
      dockerfile: Dockerfile
      # dockerfile: Dockerfile_apple_slicon
      args:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - DB_HOST=${DB_HOST}
        - DB_NAME=${DB_NAME}
        - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
        - AWS_ACCESS_KEY_ID=${MINIO_USER_NAME}
        - AWS_SECRET_ACCESS_KEY=${MINIO_USER_PASS}
        - DEFAULT_ARTIFACT_ROOT=s3://mlflow/
    image: mlflow-tracking:1.0
    ports:
      - "5001:5001"
    depends_on:
      - db-server
      - waitfordb
      - minio

  minio:
    image: minio/minio:RELEASE.2022-08-13T21-54-44Z
    environment:
      - MINIO_ROOT_USER=${MINIO_USER_NAME}
      - MINIO_ROOT_PASSWORD=${MINIO_USER_PASS}
    command: server --console-address ':9001' /data
    volumes:
      - ./buckets:/data
    ports:
      - 9000:9000
      - 9001:9001
    